/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CalculadoraVisual;

/**
 *
 * @author isaac
 */
import net.objecthunter.exp4j.Expression;
import net.objecthunter.exp4j.ExpressionBuilder;
public class CalculadoraNormal extends javax.swing.JFrame {

    /**
     * Creates new form CalculadoraNormal
     */
    public CalculadoraNormal() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtcalculadora = new javax.swing.JTextField();
        btnRetroceder = new javax.swing.JButton();
        btnCE = new javax.swing.JButton();
        btnC = new javax.swing.JButton();
        btnResultado = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnPunto = new javax.swing.JButton();
        btnMultiplicacion = new javax.swing.JButton();
        btnSuma = new javax.swing.JButton();
        btnresta = new javax.swing.JButton();
        btnDivision = new javax.swing.JButton();
        btnPorcentaje = new javax.swing.JButton();
        btncambiodesigno = new javax.swing.JButton();
        btnfraccion = new javax.swing.JButton();
        btnSq = new javax.swing.JButton();
        btnCientifica = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);
        getContentPane().add(txtcalculadora);
        txtcalculadora.setBounds(21, 14, 750, 140);

        btnRetroceder.setText("Retroceder");
        btnRetroceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetrocederActionPerformed(evt);
            }
        });
        getContentPane().add(btnRetroceder);
        btnRetroceder.setBounds(30, 180, 130, 40);

        btnCE.setText("CE");
        btnCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCEActionPerformed(evt);
            }
        });
        getContentPane().add(btnCE);
        btnCE.setBounds(170, 180, 90, 40);

        btnC.setText("C");
        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCActionPerformed(evt);
            }
        });
        getContentPane().add(btnC);
        btnC.setBounds(270, 180, 90, 40);

        btnResultado.setText("=");
        btnResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultadoActionPerformed(evt);
            }
        });
        getContentPane().add(btnResultado);
        btnResultado.setBounds(590, 510, 110, 50);

        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        getContentPane().add(btn7);
        btn7.setBounds(30, 260, 110, 50);

        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        getContentPane().add(btn8);
        btn8.setBounds(170, 260, 110, 50);

        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        getContentPane().add(btn9);
        btn9.setBounds(310, 260, 110, 50);

        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn4);
        btn4.setBounds(30, 340, 110, 50);

        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        getContentPane().add(btn5);
        btn5.setBounds(170, 340, 110, 50);

        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        getContentPane().add(btn6);
        btn6.setBounds(310, 340, 110, 50);

        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn1);
        btn1.setBounds(30, 420, 110, 50);

        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn2);
        btn2.setBounds(170, 420, 110, 50);

        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn3);
        btn3.setBounds(310, 420, 110, 50);

        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        getContentPane().add(btn0);
        btn0.setBounds(30, 510, 110, 50);

        btnPunto.setText(".");
        btnPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuntoActionPerformed(evt);
            }
        });
        getContentPane().add(btnPunto);
        btnPunto.setBounds(170, 510, 110, 50);

        btnMultiplicacion.setText("*");
        btnMultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicacionActionPerformed(evt);
            }
        });
        getContentPane().add(btnMultiplicacion);
        btnMultiplicacion.setBounds(310, 510, 110, 50);

        btnSuma.setText("+");
        btnSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSuma);
        btnSuma.setBounds(440, 510, 110, 50);

        btnresta.setText("-");
        btnresta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrestaActionPerformed(evt);
            }
        });
        getContentPane().add(btnresta);
        btnresta.setBounds(440, 420, 110, 50);

        btnDivision.setText("/");
        btnDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivisionActionPerformed(evt);
            }
        });
        getContentPane().add(btnDivision);
        btnDivision.setBounds(440, 340, 110, 50);

        btnPorcentaje.setText("%");
        btnPorcentaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPorcentajeActionPerformed(evt);
            }
        });
        getContentPane().add(btnPorcentaje);
        btnPorcentaje.setBounds(440, 260, 110, 50);

        btncambiodesigno.setText("+/-");
        btncambiodesigno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncambiodesignoActionPerformed(evt);
            }
        });
        getContentPane().add(btncambiodesigno);
        btncambiodesigno.setBounds(590, 260, 110, 50);

        btnfraccion.setText("1/x");
        btnfraccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfraccionActionPerformed(evt);
            }
        });
        getContentPane().add(btnfraccion);
        btnfraccion.setBounds(590, 340, 110, 50);

        btnSq.setText("sq");
        btnSq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSqActionPerformed(evt);
            }
        });
        getContentPane().add(btnSq);
        btnSq.setBounds(590, 420, 110, 50);

        btnCientifica.setText("Calculadora Cientifica");
        btnCientifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCientificaActionPerformed(evt);
            }
        });
        getContentPane().add(btnCientifica);
        btnCientifica.setBounds(450, 170, 250, 40);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRetrocederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetrocederActionPerformed
        // TODO add your handling code here:
        //eliminar el ultimo caracter
        String cadena;
        cadena = txtcalculadora.getText();
        if(cadena.length()>0){
            cadena = cadena.substring(0, cadena.length()-1);
            txtcalculadora.setText(cadena);
        }


    }//GEN-LAST:event_btnRetrocederActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        //agregar el numero 5
        txtcalculadora.setText(txtcalculadora.getText()+"5");

    }//GEN-LAST:event_btn5ActionPerformed

    private void btnCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCEActionPerformed
        // TODO add your handling code here:
        //limpiar la pantalla
        txtcalculadora.setText("");

    }//GEN-LAST:event_btnCEActionPerformed

    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCActionPerformed
        // TODO add your handling code here:
        //limpiar la pantalla
        txtcalculadora.setText("");
    }//GEN-LAST:event_btnCActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
        //agregar el numero 7
        txtcalculadora.setText(txtcalculadora.getText()+"7");
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
        //agregar el numero 8
        txtcalculadora.setText(txtcalculadora.getText()+"8");

    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
        //agregar el numero 9
        txtcalculadora.setText(txtcalculadora.getText()+"9");
    }//GEN-LAST:event_btn9ActionPerformed

    private void btnPorcentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPorcentajeActionPerformed
        // TODO add your handling code here:
        //calcula el porcentaje
        String cadena;
        Double num;
        cadena = txtcalculadora.getText();
        if(cadena.length()>0){
            num = Double.parseDouble(cadena)/100;
            txtcalculadora.setText(num.toString());
        }



    }//GEN-LAST:event_btnPorcentajeActionPerformed

    private void btncambiodesignoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncambiodesignoActionPerformed
        // TODO add your handling code here:
        //cambia el signo
        String cadena;
        Double num;
        cadena = txtcalculadora.getText();
        if(cadena.length()>0){
            num = (-1)*Double.parseDouble(cadena);
            txtcalculadora.setText(num.toString());
        }


    }//GEN-LAST:event_btncambiodesignoActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        //agregar el numero 4
        txtcalculadora.setText(txtcalculadora.getText()+"4");

    }//GEN-LAST:event_btn4ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
        //agregar el numero 6
        txtcalculadora.setText(txtcalculadora.getText()+"6");

    }//GEN-LAST:event_btn6ActionPerformed

    private void btnDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivisionActionPerformed
        // TODO add your handling code here:
        //agregar la division
        String cadena;
        cadena = txtcalculadora.getText();
        if(cadena.length()>0){
            if(cadena.charAt(cadena.length()-1) != '/'){
                txtcalculadora.setText(txtcalculadora.getText()+"/");
            } else {
                txtcalculadora.setText(cadena);

            }
        }




    }//GEN-LAST:event_btnDivisionActionPerformed

    private void btnfraccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfraccionActionPerformed
        // TODO add your handling code here:
        //calcula la fraccion
        String cadena;
        Double num;
        cadena = txtcalculadora.getText();
        if(cadena.length()>0){
            num = 1/(Double.parseDouble(cadena));
            txtcalculadora.setText(num.toString());
        }

    }//GEN-LAST:event_btnfraccionActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        //agregar el numero 1
        txtcalculadora.setText(txtcalculadora.getText()+"1");

    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        //agregar el numero 2
        txtcalculadora.setText(txtcalculadora.getText()+"2");

    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        //agregar el numero 3
        txtcalculadora.setText(txtcalculadora.getText()+"3");

    }//GEN-LAST:event_btn3ActionPerformed

    private void btnrestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrestaActionPerformed
        // TODO add your handling code here:
        //agregar la resta
        String cadena;
        cadena = txtcalculadora.getText();
        if(cadena.length()>0){
            if(cadena.charAt(cadena.length()-1) != '-'){
                txtcalculadora.setText(txtcalculadora.getText()+"-");
            } else {
                txtcalculadora.setText(cadena);

            }
        }

    }//GEN-LAST:event_btnrestaActionPerformed

    private void btnSqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSqActionPerformed
        // TODO add your handling code here:
        //calcula la raiz cuadrada
        try {
            String input = "sqrt(" + txtcalculadora.getText() + ")";
            Expression expression = new ExpressionBuilder(input).build();
            double result = expression.evaluate();
            txtcalculadora.setText(Double.toString(result));
        } catch (Exception e) {
            txtcalculadora.setText("Error");
        }
    }//GEN-LAST:event_btnSqActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        // TODO add your handling code here:
        //agregar el numero 0
        txtcalculadora.setText(txtcalculadora.getText()+"0");


    }//GEN-LAST:event_btn0ActionPerformed

    private void btnPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuntoActionPerformed
        // TODO add your handling code here:
        //agregar el punto
        String cadena;
        cadena = txtcalculadora.getText();
        if(cadena.length()>0){
            if(cadena.charAt(cadena.length()-1) != '.'){
                txtcalculadora.setText(txtcalculadora.getText()+".");
            } else {
                txtcalculadora.setText(cadena);

            }
        }

    }//GEN-LAST:event_btnPuntoActionPerformed

    private void btnMultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicacionActionPerformed
        // TODO add your handling code here:
        //agregar la multiplicacion
        String cadena;
        cadena = txtcalculadora.getText();
        if(cadena.length()>0){
            if(cadena.charAt(cadena.length()-1) != '*'){
                txtcalculadora.setText(txtcalculadora.getText()+"*");
            } else {
                txtcalculadora.setText(cadena);

            }
        }

    }//GEN-LAST:event_btnMultiplicacionActionPerformed

    private void btnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumaActionPerformed
        // TODO add your handling code here:
        //agregar la suma
        String cadena;
        cadena = txtcalculadora.getText();
        if(cadena.length()>0){
            if(cadena.charAt(cadena.length()-1) != '+'){
                txtcalculadora.setText(txtcalculadora.getText()+"+");
            } else {
                txtcalculadora.setText(cadena);

            }
        }

    }//GEN-LAST:event_btnSumaActionPerformed

    private void btnResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultadoActionPerformed
        // TODO add your handling code here:
        try {
            String input = txtcalculadora.getText();
            Expression expression = new ExpressionBuilder(input).build();
            double result = expression.evaluate();
            txtcalculadora.setText(Double.toString(result));
        } catch (Exception e) {
            txtcalculadora.setText("Error");
        }

    }//GEN-LAST:event_btnResultadoActionPerformed

    private void btnCientificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCientificaActionPerformed
        // TODO add your handling code here:

        CalculadoraCientifica calculadoraCientifica = new CalculadoraCientifica();
        calculadoraCientifica.setVisible(true);
        this.setVisible(false);





    }//GEN-LAST:event_btnCientificaActionPerformed

    //evento del boton de la calculadora cientifica
    



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraNormal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraNormal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraNormal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraNormal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraNormal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnCE;
    private javax.swing.JButton btnCientifica;
    private javax.swing.JButton btnDivision;
    private javax.swing.JButton btnMultiplicacion;
    private javax.swing.JButton btnPorcentaje;
    private javax.swing.JButton btnPunto;
    private javax.swing.JButton btnResultado;
    private javax.swing.JButton btnRetroceder;
    private javax.swing.JButton btnSq;
    private javax.swing.JButton btnSuma;
    private javax.swing.JButton btncambiodesigno;
    private javax.swing.JButton btnfraccion;
    private javax.swing.JButton btnresta;
    private javax.swing.JTextField txtcalculadora;
    // End of variables declaration//GEN-END:variables
}
