/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CalculadoraVisual;

import org.mariuszgromada.math.mxparser.Expression;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author viejo
 */
public class CalculadoraCientifica extends JFrame {

    /**
     * Creates new form CalculadoraCientifica
     */
    public CalculadoraCientifica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCalculadora = new javax.swing.JTextField();
        bntCalculadoraNormal = new javax.swing.JButton();
        RadiosCm = new javax.swing.JRadioButton();
        radioRadian = new javax.swing.JRadioButton();
        btnResultado = new javax.swing.JButton();
        btnRetroceder = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btnfraccion = new javax.swing.JButton();
        btnCambioSigno = new javax.swing.JButton();
        btnPunto = new javax.swing.JButton();
        btnSumar = new javax.swing.JButton();
        btnRestar = new javax.swing.JButton();
        btnMultiplicar = new javax.swing.JButton();
        btnDivision = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnCE = new javax.swing.JButton();
        btnC = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btngsm = new javax.swing.JButton();
        btnexp = new javax.swing.JButton();
        btnIN = new javax.swing.JButton();
        btnsin = new javax.swing.JButton();
        btncos = new javax.swing.JButton();
        btntan = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        btnxy = new javax.swing.JButton();
        btnx3 = new javax.swing.JButton();
        btnx2 = new javax.swing.JButton();
        btnlog = new javax.swing.JButton();
        btnN = new javax.swing.JButton();
        btnparentecis = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);
        getContentPane().add(txtCalculadora);
        txtCalculadora.setBounds(20, 50, 740, 50);

        bntCalculadoraNormal.setText("calculadora normal");
        bntCalculadoraNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCalculadoraNormalActionPerformed(evt);
            }
        });
        getContentPane().add(bntCalculadoraNormal);
        bntCalculadoraNormal.setBounds(550, 10, 150, 23);

        //grupo de botones
        ButtonGroup opcion = new ButtonGroup();

        opcion.add(RadiosCm);
        RadiosCm.setText("Centimetros");
        RadiosCm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadiosCmActionPerformed(evt);
            }
        });
        getContentPane().add(RadiosCm);
        RadiosCm.setBounds(30, 180, 88, 21);

        opcion.add(radioRadian);
        radioRadian.setText("Radianes");
        radioRadian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioRadianActionPerformed(evt);
            }
        });
        getContentPane().add(radioRadian);
        radioRadian.setBounds(160, 180, 70, 21);

        btnResultado.setText("=");
        btnResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultadoActionPerformed(evt);
            }
        });
        getContentPane().add(btnResultado);
        btnResultado.setBounds(610, 430, 130, 30);

        btnRetroceder.setText("Retroceso");
        btnRetroceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetrocederActionPerformed(evt);
            }
        });
        getContentPane().add(btnRetroceder);
        btnRetroceder.setBounds(370, 130, 130, 30);

        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        getContentPane().add(btn7);
        btn7.setBounds(370, 180, 80, 30);

        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        getContentPane().add(btn8);
        btn8.setBounds(480, 180, 80, 30);

        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn4);
        btn4.setBounds(370, 240, 80, 30);

        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        getContentPane().add(btn5);
        btn5.setBounds(480, 240, 80, 30);

        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        getContentPane().add(btn6);
        btn6.setBounds(590, 240, 80, 30);

        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn1);
        btn1.setBounds(370, 300, 80, 30);

        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn2);
        btn2.setBounds(480, 300, 80, 30);

        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn3);
        btn3.setBounds(590, 300, 80, 30);

        btnfraccion.setText("1/x");
        btnfraccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfraccionActionPerformed(evt);
            }
        });
        getContentPane().add(btnfraccion);
        btnfraccion.setBounds(230, 420, 80, 30);

        btnCambioSigno.setText("+/-");
        btnCambioSigno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambioSignoActionPerformed(evt);
            }
        });
        getContentPane().add(btnCambioSigno);
        btnCambioSigno.setBounds(480, 360, 80, 30);

        btnPunto.setText(",");
        btnPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuntoActionPerformed(evt);
            }
        });
        getContentPane().add(btnPunto);
        btnPunto.setBounds(590, 360, 80, 30);

        btnSumar.setText("+");
        btnSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSumar);
        btnSumar.setBounds(690, 360, 80, 30);

        btnRestar.setText("-");
        btnRestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRestar);
        btnRestar.setBounds(690, 300, 80, 30);

        btnMultiplicar.setText("*");
        btnMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicarActionPerformed(evt);
            }
        });
        getContentPane().add(btnMultiplicar);
        btnMultiplicar.setBounds(690, 240, 80, 30);

        btnDivision.setText("/");
        btnDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivisionActionPerformed(evt);
            }
        });
        getContentPane().add(btnDivision);
        btnDivision.setBounds(690, 180, 80, 30);

        jButton18.setText("Retroceso");
        getContentPane().add(jButton18);
        jButton18.setBounds(370, 130, 130, 30);

        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        getContentPane().add(btn9);
        btn9.setBounds(590, 180, 80, 30);

        btnCE.setText("CE");
        btnCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCEActionPerformed(evt);
            }
        });
        getContentPane().add(btnCE);
        btnCE.setBounds(530, 130, 80, 30);

        btnC.setText("C");
        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCActionPerformed(evt);
            }
        });
        getContentPane().add(btnC);
        btnC.setBounds(640, 130, 80, 30);

        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        getContentPane().add(btn0);
        btn0.setBounds(370, 360, 80, 30);

        btngsm.setText("gsm");
        btngsm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngsmActionPerformed(evt);
            }
        });
        getContentPane().add(btngsm);
        btngsm.setBounds(30, 240, 80, 30);

        btnexp.setText("exp");
        btnexp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexpActionPerformed(evt);
            }
        });
        getContentPane().add(btnexp);
        btnexp.setBounds(130, 240, 80, 30);

        btnIN.setText("In");
        btnIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnINActionPerformed(evt);
            }
        });
        getContentPane().add(btnIN);
        btnIN.setBounds(230, 240, 80, 30);

        btnsin.setText("Sin");
        btnsin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsinActionPerformed(evt);
            }
        });
        getContentPane().add(btnsin);
        btnsin.setBounds(30, 300, 80, 30);

        btncos.setText("Cos");
        btncos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncosActionPerformed(evt);
            }
        });
        getContentPane().add(btncos);
        btncos.setBounds(30, 360, 80, 30);

        btntan.setText("Tan");
        btntan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntanActionPerformed(evt);
            }
        });
        getContentPane().add(btntan);
        btntan.setBounds(30, 420, 80, 30);

        jButton29.setText("Tan");
        getContentPane().add(jButton29);
        jButton29.setBounds(30, 420, 80, 30);

        btnxy.setText("x^y");
        btnxy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxyActionPerformed(evt);
            }
        });
        getContentPane().add(btnxy);
        btnxy.setBounds(130, 300, 80, 30);

        btnx3.setText("x^3");
        btnx3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnx3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnx3);
        btnx3.setBounds(130, 360, 80, 30);

        btnx2.setText("x^2");
        btnx2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnx2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnx2);
        btnx2.setBounds(130, 420, 80, 30);

        btnlog.setText("log");
        btnlog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogActionPerformed(evt);
            }
        });
        getContentPane().add(btnlog);
        btnlog.setBounds(230, 300, 80, 30);

        btnN.setText("n!");
        btnN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNActionPerformed(evt);
            }
        });
        getContentPane().add(btnN);
        btnN.setBounds(230, 360, 80, 30);

        btnparentecis.setText(")");
        btnparentecis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnparentecisActionPerformed(evt);
            }
        });
        getContentPane().add(btnparentecis);
        btnparentecis.setBounds(30, 470, 23, 23);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnfraccionActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnfraccionActionPerformed
        // TODO add your handling code here:
        //calcular la fraccion del numero
        double numero = Double.parseDouble(txtCalculadora.getText());
        double resultado = 1 / numero;
        txtCalculadora.setText(String.valueOf(resultado));



    }//GEN-LAST:event_btnfraccionActionPerformed

    private void btnxyActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnxyActionPerformed
        // TODO add your handling code here:
        //agrega el signo de potencia
        txtCalculadora.setText(txtCalculadora.getText() + "^");


    }//GEN-LAST:event_btnxyActionPerformed

    private void btnx3ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnx3ActionPerformed
        // TODO add your handling code here:
        //agrega el signo de potencia agregando el numero 3
        txtCalculadora.setText(txtCalculadora.getText() + "^3");

    }//GEN-LAST:event_btnx3ActionPerformed

    private void btnx2ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnx2ActionPerformed
        // TODO add your handling code here:
        //agrega el signo de potencia agregando el numero 2
        txtCalculadora.setText(txtCalculadora.getText() + "^2");
    }//GEN-LAST:event_btnx2ActionPerformed

    private void btnlogActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnlogActionPerformed
        // TODO add your handling code here:
        //agrega el simbolode logaritmo
        txtCalculadora.setText(txtCalculadora.getText() + "log(");

    }//GEN-LAST:event_btnlogActionPerformed

    private void btnNActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnNActionPerformed
        // TODO add your handling code here:
        //agrega el simbolo de factorial
        txtCalculadora.setText(txtCalculadora.getText() + "!");
    }//GEN-LAST:event_btnNActionPerformed

    private void bntCalculadoraNormalActionPerformed(ActionEvent evt) {//GEN-FIRST:event_bntCalculadoraNormalActionPerformed
        // TODO add your handling code here:



        new CalculadoraNormal().setVisible(true);
        this.dispose();
        CalculadoraCientifica calculadoraCientifica = new CalculadoraCientifica();
        calculadoraCientifica.setVisible(false);





    }//GEN-LAST:event_bntCalculadoraNormalActionPerformed

    private void btnRetrocederActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnRetrocederActionPerformed
        // TODO add your handling code here:
        //retrocede un caracter
        String cadena = txtCalculadora.getText();
        if (cadena.length() > 0) {
            cadena = cadena.substring(0, cadena.length() - 1);
            txtCalculadora.setText(cadena);
        }

    }//GEN-LAST:event_btnRetrocederActionPerformed

    private void btnCEActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnCEActionPerformed
        // TODO add your handling code here:
        //limpia la pantalla
        txtCalculadora.setText("");

    }//GEN-LAST:event_btnCEActionPerformed

    private void btnCActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnCActionPerformed
        // TODO add your handling code here:
        //limpia la pantalla
        txtCalculadora.setText("");

    }//GEN-LAST:event_btnCActionPerformed

    private void RadiosCmActionPerformed(ActionEvent evt) {//GEN-FIRST:event_RadiosCmActionPerformed
        // TODO add your handling code here:
        //cambia la unidad de medida a centimetros
        double metros = Double.parseDouble(txtCalculadora.getText());
        double centimetros = metros * 100;
        txtCalculadora.setText(String.valueOf(centimetros));

    }//GEN-LAST:event_RadiosCmActionPerformed

    private void radioRadianActionPerformed(ActionEvent evt) {//GEN-FIRST:event_radioRadianActionPerformed
        // TODO add your handling code here:
        //cambia la unidad de medida a radianes
        double grados = Double.parseDouble(txtCalculadora.getText());
        double radianes = Math.toRadians(grados);
        txtCalculadora.setText(String.valueOf(radianes));

    }//GEN-LAST:event_radioRadianActionPerformed

    private void btngsmActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btngsmActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btngsmActionPerformed

    private void btnexpActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnexpActionPerformed
        // TODO add your handling code here:
        //agrega notacion cientifica 10^
        txtCalculadora.setText(txtCalculadora.getText() + "10^");

    }//GEN-LAST:event_btnexpActionPerformed

    private void btnINActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnINActionPerformed
        // TODO add your handling code here:
        //agrega el simbolo de logaritmo natural
        txtCalculadora.setText(txtCalculadora.getText() + "ln(");

    }//GEN-LAST:event_btnINActionPerformed

    private void btnsinActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnsinActionPerformed
        // TODO add your handling code here:
        //agrega el simbolo de seno
        txtCalculadora.setText(txtCalculadora.getText() + "sin(");

    }//GEN-LAST:event_btnsinActionPerformed

    private void btncosActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btncosActionPerformed
        // TODO add your handling code here:
        //agrega el simbolo de coseno
        txtCalculadora.setText(txtCalculadora.getText() + "cos(");

    }//GEN-LAST:event_btncosActionPerformed

    private void btntanActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btntanActionPerformed
        // TODO add your handling code here:
        //agrega el simbolo de tangente
        txtCalculadora.setText(txtCalculadora.getText() + "tan(");

    }//GEN-LAST:event_btntanActionPerformed

    private void btn7ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
        //agrega el numero 7
        txtCalculadora.setText(txtCalculadora.getText() + "7");

    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
        //agrega el numero 8
        txtCalculadora.setText(txtCalculadora.getText() + "8");

    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
        //agrega el numero 9
        txtCalculadora.setText(txtCalculadora.getText() + "9");

    }//GEN-LAST:event_btn9ActionPerformed

    private void btnDivisionActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnDivisionActionPerformed
        // TODO add your handling code here:
        //agrega el simbolo de division
        txtCalculadora.setText(txtCalculadora.getText() + "/");
    }//GEN-LAST:event_btnDivisionActionPerformed

    private void btn4ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        //agrega el numero 4
        txtCalculadora.setText(txtCalculadora.getText() + "4");

    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        //agrega el numero 5
        txtCalculadora.setText(txtCalculadora.getText() + "5");
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
        //agrega el numero 6
        txtCalculadora.setText(txtCalculadora.getText() + "6");

    }//GEN-LAST:event_btn6ActionPerformed

    private void btnMultiplicarActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnMultiplicarActionPerformed
        // TODO add your handling code here:
        //agrega el simbolo de multiplicacion
        txtCalculadora.setText(txtCalculadora.getText() + "*");

    }//GEN-LAST:event_btnMultiplicarActionPerformed

    private void btn1ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        //agrega el numero 1
        txtCalculadora.setText(txtCalculadora.getText() + "1");

    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        //agrega el numero 2
        txtCalculadora.setText(txtCalculadora.getText() + "2");

    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        //agrega el numero 3
        txtCalculadora.setText(txtCalculadora.getText() + "3");

    }//GEN-LAST:event_btn3ActionPerformed

    private void btnRestarActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnRestarActionPerformed
        // TODO add your handling code here:
        //agrega el simbolo de resta
        txtCalculadora.setText(txtCalculadora.getText() + "-");

    }//GEN-LAST:event_btnRestarActionPerformed

    private void btn0ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        // TODO add your handling code here:
        //agrega el numero 0
        txtCalculadora.setText(txtCalculadora.getText() + "0");

    }//GEN-LAST:event_btn0ActionPerformed

    private void btnCambioSignoActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnCambioSignoActionPerformed
        // TODO add your handling code here:
        //cambia el signo del numero
        double numero = Double.parseDouble(txtCalculadora.getText());
        numero = numero * -1;
        txtCalculadora.setText(String.valueOf(numero));

    }//GEN-LAST:event_btnCambioSignoActionPerformed

    private void btnPuntoActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnPuntoActionPerformed
        // TODO add your handling code here:
        //agrega el punto decimal
        txtCalculadora.setText(txtCalculadora.getText() + ".");

    }//GEN-LAST:event_btnPuntoActionPerformed

    private void btnSumarActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnSumarActionPerformed
        // TODO add your handling code here:
        //agrega el simbolo de suma
        txtCalculadora.setText(txtCalculadora.getText() + "+");

    }//GEN-LAST:event_btnSumarActionPerformed

    private void btnResultadoActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnResultadoActionPerformed
        // TODO add your handling code here:
        String expressionStr = txtCalculadora.getText();
        Expression expression = new Expression(expressionStr);
        double result = expression.calculate();
        txtCalculadora.setText(Double.toString(result));


    }//GEN-LAST:event_btnResultadoActionPerformed

    private void btnparentecisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnparentecisActionPerformed
        // TODO add your handling code here:
        //agrega el simbolo de parentesis
        txtCalculadora.setText(txtCalculadora.getText() + ")");

    }//GEN-LAST:event_btnparentecisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CalculadoraCientifica.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(CalculadoraCientifica.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(CalculadoraCientifica.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(CalculadoraCientifica.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraCientifica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RadiosCm;
    private javax.swing.JButton bntCalculadoraNormal;
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnCE;
    private javax.swing.JButton btnCambioSigno;
    private javax.swing.JButton btnDivision;
    private javax.swing.JButton btnIN;
    private javax.swing.JButton btnMultiplicar;
    private javax.swing.JButton btnN;
    private javax.swing.JButton btnPunto;
    private javax.swing.JButton btnRestar;
    private javax.swing.JButton btnResultado;
    private javax.swing.JButton btnRetroceder;
    private javax.swing.JButton btnSumar;
    private javax.swing.JButton btncos;
    private javax.swing.JButton btnexp;
    private javax.swing.JButton btnfraccion;
    private javax.swing.JButton btngsm;
    private javax.swing.JButton btnlog;
    private javax.swing.JButton btnparentecis;
    private javax.swing.JButton btnsin;
    private javax.swing.JButton btntan;
    private javax.swing.JButton btnx2;
    private javax.swing.JButton btnx3;
    private javax.swing.JButton btnxy;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton29;
    private javax.swing.JRadioButton radioRadian;
    private javax.swing.JTextField txtCalculadora;
    // End of variables declaration//GEN-END:variables
}
