/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CURP;

/**
 *
 * @author isaac
 */
public class GeneradorDeCurp extends javax.swing.JFrame {

    /**
     * Creates new form GeneradorDeCurp
     */
    public GeneradorDeCurp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtPaterno = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtMaterno = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        spinerDiaz = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        spinerMes = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        spinerAÑo = new javax.swing.JSpinner();
        radiosMasculino = new javax.swing.JRadioButton();
        radioFemenino = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnCurp = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        setMaximumSize(new java.awt.Dimension(800, 800));
        setMinimumSize(new java.awt.Dimension(800, 800));
        setPreferredSize(new java.awt.Dimension(800, 800));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 800));
        getContentPane().setLayout(null);

        jLabel1.setText("Apellido Paterno");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 50, 150, 19);

        txtPaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPaternoActionPerformed(evt);
            }
        });
        getContentPane().add(txtPaterno);
        txtPaterno.setBounds(230, 50, 230, 25);

        jLabel2.setText("Apellido Materno");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 90, 150, 19);

        txtMaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaternoActionPerformed(evt);
            }
        });
        getContentPane().add(txtMaterno);
        txtMaterno.setBounds(230, 90, 230, 25);

        jLabel3.setText("Nombres");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 140, 150, 19);

        txtNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombresActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombres);
        txtNombres.setBounds(230, 140, 230, 25);

        jLabel4.setText("Dia");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(100, 210, 48, 19);
        getContentPane().add(spinerDiaz);
        spinerDiaz.setBounds(90, 240, 64, 25);

        jLabel5.setText("Mes");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(210, 210, 47, 19);
        getContentPane().add(spinerMes);
        spinerMes.setBounds(190, 240, 64, 25);

        jLabel6.setText("Año");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(290, 210, 25, 19);
        getContentPane().add(spinerAÑo);
        spinerAÑo.setBounds(280, 240, 120, 25);

        radiosMasculino.setText("Masculino");
        radiosMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiosMasculinoActionPerformed(evt);
            }
        });
        getContentPane().add(radiosMasculino);
        radiosMasculino.setBounds(260, 310, 140, 23);

        radioFemenino.setText("Femenino");
        getContentPane().add(radioFemenino);
        radioFemenino.setBounds(430, 310, 88, 23);

        jLabel7.setText("Genero");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(90, 310, 100, 19);

        jLabel8.setText("Estado De la republica Mexicana");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(90, 400, 240, 19);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(370, 400, 270, 25);

        jLabel9.setText("CURP");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(90, 490, 90, 19);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(90, 530, 510, 30);

        btnCurp.setText("Generar CURP");
        getContentPane().add(btnCurp);
        btnCurp.setBounds(440, 640, 160, 25);

        btnSalir.setText("Salir");
        getContentPane().add(btnSalir);
        btnSalir.setBounds(140, 640, 150, 25);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(70, 280, 540, 90);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPaternoActionPerformed

    private void txtMaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaternoActionPerformed

    private void txtNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombresActionPerformed

    private void radiosMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiosMasculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radiosMasculinoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GeneradorDeCurp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GeneradorDeCurp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GeneradorDeCurp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GeneradorDeCurp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GeneradorDeCurp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCurp;
    private javax.swing.JButton btnSalir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JRadioButton radioFemenino;
    private javax.swing.JRadioButton radiosMasculino;
    private javax.swing.JSpinner spinerAÑo;
    private javax.swing.JSpinner spinerDiaz;
    private javax.swing.JSpinner spinerMes;
    private javax.swing.JTextField txtMaterno;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtPaterno;
    // End of variables declaration//GEN-END:variables
}
